name: github
description: Apllication to view GitHub Repo and files

#PJohNSK - Github

version: 0.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  get_it: 1.0.3+2
  shared_preferences: ^0.5.4+6
  provider: ^3.0.0+1
  cached_network_image: ^2.0.0-rc.1
  flutter_secure_storage: ^3.3.1+1
  device_info: ^0.4.1+4
  flutter_datetime_picker: ^1.4.0
  package_info: ^0.4.0+14
  fluttertoast: ^3.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/country_code.json
    - assets/images/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSansRegular.ttf